/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiIO */

#ifndef _Included_imgui_ImGuiIO
#define _Included_imgui_ImGuiIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetConfigFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetBackendFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetBackendFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetBackendFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetBackendFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDisplaySize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nGetDisplaySize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDisplaySizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetDisplaySizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDisplaySizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetDisplaySizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetDisplaySize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetDisplaySize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDeltaTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetDeltaTime
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetDeltaTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetDeltaTime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetIniSavingRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetIniSavingRate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetIniSavingRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetIniSavingRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetIniFilename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_nGetIniFilename
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetIniFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetIniFilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetLogFilename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_nGetLogFilename
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetLogFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetLogFilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetFonts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiIO_nGetFonts
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFonts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFonts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetFontGlobalScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetFontGlobalScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFontGlobalScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFontGlobalScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetFontAllowUserScaling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetFontAllowUserScaling
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFontAllowUserScaling
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFontAllowUserScaling
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetFontDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiIO_nGetFontDefault
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFontDefault
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFontDefault
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDisplayFramebufferScale
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nGetDisplayFramebufferScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDisplayFramebufferScaleX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetDisplayFramebufferScaleX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetDisplayFramebufferScaleY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetDisplayFramebufferScaleY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetDisplayFramebufferScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetDisplayFramebufferScale
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDockingNoSplit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDockingNoSplit
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDockingNoSplit
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDockingNoSplit
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDockingNoDockingOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDockingNoDockingOver
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDockingNoDockingOver
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDockingNoDockingOver
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDockingWithShift
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDockingWithShift
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDockingWithShift
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDockingWithShift
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDockingAlwaysTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDockingAlwaysTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDockingAlwaysTabBar
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDockingAlwaysTabBar
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDockingTransparentPayload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDockingTransparentPayload
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDockingTransparentPayload
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDockingTransparentPayload
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigViewportsNoAutoMerge
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigViewportsNoAutoMerge
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigViewportsNoAutoMerge
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigViewportsNoAutoMerge
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigViewportsNoTaskBarIcon
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigViewportsNoTaskBarIcon
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigViewportsNoTaskBarIcon
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigViewportsNoTaskBarIcon
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigViewportsNoDecoration
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigViewportsNoDecoration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigViewportsNoDecoration
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigViewportsNoDecoration
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigViewportsNoDefaultParent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigViewportsNoDefaultParent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigViewportsNoDefaultParent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigViewportsNoDefaultParent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDpiScaleFonts
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDpiScaleFonts
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDpiScaleFonts
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDpiScaleFonts
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDpiScaleViewports
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDpiScaleViewports
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDpiScaleViewports
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDpiScaleViewports
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigErrorRecovery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigErrorRecovery
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigErrorRecovery
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigErrorRecovery
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigErrorRecoveryEnableAssert
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigErrorRecoveryEnableAssert
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigErrorRecoveryEnableAssert
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigErrorRecoveryEnableAssert
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigErrorRecoveryEnableDebugLog
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigErrorRecoveryEnableDebugLog
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigErrorRecoveryEnableDebugLog
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigErrorRecoveryEnableDebugLog
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigErrorRecoveryEnableTooltip
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigErrorRecoveryEnableTooltip
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigErrorRecoveryEnableTooltip
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigErrorRecoveryEnableTooltip
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDebugHighlightIdConflicts
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDebugHighlightIdConflicts
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDebugHighlightIdConflicts
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDebugHighlightIdConflicts
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDrawCursor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseDrawCursor
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDrawCursor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDrawCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigMacOSXBehaviors
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigMacOSXBehaviors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigMacOSXBehaviors
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigMacOSXBehaviors
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigInputTrickleEventQueue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigInputTrickleEventQueue
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigInputTrickleEventQueue
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigInputTrickleEventQueue
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigInputTextCursorBlink
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigInputTextCursorBlink
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigInputTextCursorBlink
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigInputTextCursorBlink
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigInputTextEnterKeepActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigInputTextEnterKeepActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigInputTextEnterKeepActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigInputTextEnterKeepActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDragClickToInputText
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDragClickToInputText
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDragClickToInputText
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDragClickToInputText
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigWindowsResizeFromEdges
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigWindowsResizeFromEdges
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigWindowsResizeFromEdges
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigWindowsResizeFromEdges
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigWindowsMoveFromTitleBarOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigWindowsMoveFromTitleBarOnly
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigWindowsMoveFromTitleBarOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigWindowsMoveFromTitleBarOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigMemoryCompactTimer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigMemoryCompactTimer
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigMemoryCompactTimer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigMemoryCompactTimer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDoubleClickTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDoubleClickTime
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDoubleClickTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDoubleClickTime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDoubleClickMaxDist
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDoubleClickMaxDist
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDoubleClickMaxDist
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDoubleClickMaxDist
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDragThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDragThreshold
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDragThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDragThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeyRepeatDelay
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetKeyRepeatDelay
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyRepeatDelay
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyRepeatDelay
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeyRepeatRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetKeyRepeatRate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyRepeatRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyRepeatRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDebugIsDebuggerPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDebugIsDebuggerPresent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDebugIsDebuggerPresent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDebugIsDebuggerPresent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDebugBeginReturnValueOnce
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDebugBeginReturnValueOnce
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDebugBeginReturnValueOnce
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDebugBeginReturnValueOnce
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDebugBeginReturnValueLoop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDebugBeginReturnValueLoop
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDebugBeginReturnValueLoop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDebugBeginReturnValueLoop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDebugIgnoreFocusLoss
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDebugIgnoreFocusLoss
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDebugIgnoreFocusLoss
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDebugIgnoreFocusLoss
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetConfigDebugIniSettings
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetConfigDebugIniSettings
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetConfigDebugIniSettings
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetConfigDebugIniSettings
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetBackendPlatformName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_nGetBackendPlatformName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetBackendPlatformName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetBackendPlatformName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetBackendRendererName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_nGetBackendRendererName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetBackendRendererName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetBackendRendererName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setSetClipboardTextFn
 * Signature: (Limgui/callback/ImStrConsumer;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setSetClipboardTextFn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setGetClipboardTextFn
 * Signature: (Limgui/callback/ImStrSupplier;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setGetClipboardTextFn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddKeyEvent
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddKeyEvent
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddKeyAnalogEvent
 * Signature: (IZF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddKeyAnalogEvent
  (JNIEnv *, jobject, jint, jboolean, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddMousePosEvent
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddMousePosEvent
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddMouseButtonEvent
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddMouseButtonEvent
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddMouseWheelEvent
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddMouseWheelEvent
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddMouseSourceEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddMouseSourceEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddMouseViewportEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddMouseViewportEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddFocusEvent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddFocusEvent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddInputCharacter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddInputCharacter
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddInputCharacterUTF16
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddInputCharacterUTF16
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nAddInputCharactersUTF8
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nAddInputCharactersUTF8
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyEventNativeData
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyEventNativeData__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyEventNativeData
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyEventNativeData__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetAppAcceptingEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetAppAcceptingEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nClearEventsQueue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nClearEventsQueue
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nClearInputKeys
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nClearInputKeys
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nClearInputMouse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nClearInputMouse
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetWantCaptureMouse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetWantCaptureMouse
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetWantCaptureMouse
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetWantCaptureMouse
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetWantCaptureKeyboard
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetWantCaptureKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetWantCaptureKeyboard
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetWantCaptureKeyboard
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetWantTextInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetWantTextInput
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetWantTextInput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetWantTextInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetWantSetMousePos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetWantSetMousePos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetWantSetMousePos
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetWantSetMousePos
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetWantSaveIniSettings
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetWantSaveIniSettings
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetWantSaveIniSettings
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetWantSaveIniSettings
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetNavActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetNavActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetNavActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetNavActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetNavVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetNavVisible
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetNavVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetNavVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetFramerate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetFramerate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFramerate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFramerate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMetricsRenderVertices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMetricsRenderVertices
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMetricsRenderVertices
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMetricsRenderVertices
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMetricsRenderIndices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMetricsRenderIndices
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMetricsRenderIndices
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMetricsRenderIndices
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMetricsRenderWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMetricsRenderWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMetricsRenderWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMetricsRenderWindows
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMetricsActiveWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMetricsActiveWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMetricsActiveWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMetricsActiveWindows
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDelta
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nGetMouseDelta
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDeltaX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDeltaX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDeltaY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDeltaY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDelta
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDelta
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiIO_nGetCtx
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMousePos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nGetMousePos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMousePosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMousePosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMousePosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMousePosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMousePos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMousePos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDown
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_imgui_ImGuiIO_nGetMouseDown__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseDown__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDown
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDown___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDown
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDown__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseWheel
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseWheel
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseWheel
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseWheel
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseWheelH
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseWheelH
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseWheelH
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseWheelH
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseHoveredViewport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMouseHoveredViewport
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseHoveredViewport
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseHoveredViewport
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeyCtrl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetKeyCtrl
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyCtrl
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyCtrl
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeyShift
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetKeyShift
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyShift
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyShift
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeyAlt
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetKeyAlt
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyAlt
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyAlt
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeySuper
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetKeySuper
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeySuper
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeySuper
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeyMods
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetKeyMods
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeyMods
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeyMods
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetKeysData
 * Signature: ()[Limgui/ImGuiKeyData;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_ImGuiIO_nGetKeysData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetKeysData
 * Signature: ([Limgui/ImGuiKeyData;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetKeysData
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetWantCaptureMouseUnlessPopupClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetWantCaptureMouseUnlessPopupClose
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetWantCaptureMouseUnlessPopupClose
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetWantCaptureMouseUnlessPopupClose
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMousePosPrev
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nGetMousePosPrev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMousePosPrevX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMousePosPrevX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMousePosPrevY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMousePosPrevY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMousePosPrev
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMousePosPrev
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedPos
 * Signature: ()[Limgui/ImVec2;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_ImGuiIO_nGetMouseClickedPos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedPos
 * Signature: ([Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedPos
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedTime
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_imgui_ImGuiIO_nGetMouseClickedTime__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_imgui_ImGuiIO_nGetMouseClickedTime__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedTime
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedTime___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedTime
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedTime__ID
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClicked
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_imgui_ImGuiIO_nGetMouseClicked__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClicked
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseClicked__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClicked
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClicked___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClicked
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClicked__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDoubleClicked
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_imgui_ImGuiIO_nGetMouseDoubleClicked__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDoubleClicked
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseDoubleClicked__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDoubleClicked
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDoubleClicked___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDoubleClicked
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDoubleClicked__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedCount
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_ImGuiIO_nGetMouseClickedCount__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMouseClickedCount__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedCount
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedCount___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedCount
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedCount__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedLastCount
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_ImGuiIO_nGetMouseClickedLastCount__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseClickedLastCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_nGetMouseClickedLastCount__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedLastCount
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedLastCount___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseClickedLastCount
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseClickedLastCount__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseReleased
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_imgui_ImGuiIO_nGetMouseReleased__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseReleased
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseReleased__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseReleased
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseReleased___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseReleased
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseReleased__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownOwned
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_imgui_ImGuiIO_nGetMouseDownOwned__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownOwned
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseDownOwned__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownOwned
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownOwned___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownOwned
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownOwned__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownOwnedUnlessPopupClose
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_imgui_ImGuiIO_nGetMouseDownOwnedUnlessPopupClose__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownOwnedUnlessPopupClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseDownOwnedUnlessPopupClose__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownOwnedUnlessPopupClose
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownOwnedUnlessPopupClose___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownOwnedUnlessPopupClose
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownOwnedUnlessPopupClose__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseWheelRequestAxisSwap
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseWheelRequestAxisSwap
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseWheelRequestAxisSwap
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseWheelRequestAxisSwap
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseCtrlLeftAsRightClick
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetMouseCtrlLeftAsRightClick
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseCtrlLeftAsRightClick
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseCtrlLeftAsRightClick
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownDuration
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_imgui_ImGuiIO_nGetMouseDownDuration__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownDuration
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDownDuration__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownDuration
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownDuration___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownDuration
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownDuration__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownDurationPrev
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_imgui_ImGuiIO_nGetMouseDownDurationPrev__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDownDurationPrev
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDownDurationPrev__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownDurationPrev
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownDurationPrev___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDownDurationPrev
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDownDurationPrev__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDragMaxDistanceAbs
 * Signature: ()[Limgui/ImVec2;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_ImGuiIO_nGetMouseDragMaxDistanceAbs
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDragMaxDistanceAbs
 * Signature: ([Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDragMaxDistanceAbs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDragMaxDistanceSqr
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_imgui_ImGuiIO_nGetMouseDragMaxDistanceSqr__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetMouseDragMaxDistanceSqr
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetMouseDragMaxDistanceSqr__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDragMaxDistanceSqr
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDragMaxDistanceSqr___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetMouseDragMaxDistanceSqr
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetMouseDragMaxDistanceSqr__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetPenPressure
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_nGetPenPressure
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetPenPressure
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetPenPressure
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetAppFocusLost
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetAppFocusLost
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetAppAcceptingEvents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_nGetAppAcceptingEvents
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetInputQueueSurrogate
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImGuiIO_nGetInputQueueSurrogate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetInputQueueSurrogate
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetInputQueueSurrogate
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
