/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFontAtlas */

#ifndef _Included_imgui_ImFontAtlas
#define _Included_imgui_ImFontAtlas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFontAtlas
 * Method:    nInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nInit
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFont
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefault__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefault
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefault__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefaultVector
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefaultVector__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefaultVector
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefaultVector__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefaultBitmap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefaultBitmap__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefaultBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefaultBitmap__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;FJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2FJ
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;FJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2FJ_3S
  (JNIEnv *, jobject, jstring, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;F[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2F_3S
  (JNIEnv *, jobject, jstring, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BF)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BF
  (JNIEnv *, jobject, jbyteArray, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BFJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BFJ
  (JNIEnv *, jobject, jbyteArray, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BFJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BFJ_3S
  (JNIEnv *, jobject, jbyteArray, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BF[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BF_3S
  (JNIEnv *, jobject, jbyteArray, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIF)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIF
  (JNIEnv *, jobject, jbyteArray, jint, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIFJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIFJ
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIFJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIFJ_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIF[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIF_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BF)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BF
  (JNIEnv *, jobject, jbyteArray, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BFJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BFJ
  (JNIEnv *, jobject, jbyteArray, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BFJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BFJ_3S
  (JNIEnv *, jobject, jbyteArray, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BF[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BF_3S
  (JNIEnv *, jobject, jbyteArray, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIF)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIF
  (JNIEnv *, jobject, jbyteArray, jint, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIFJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIFJ
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIFJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIFJ_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIF[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIF_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedBase85TTF
 * Signature: (Ljava/lang/String;FJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedBase85TTF__Ljava_lang_String_2FJ
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedBase85TTF
 * Signature: (Ljava/lang/String;FJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedBase85TTF__Ljava_lang_String_2FJ_3S
  (JNIEnv *, jobject, jstring, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nClearInputData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nClearInputData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nClearTexData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nClearTexData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nClearFonts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nClearFonts
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    setFreeTypeRenderer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_setFreeTypeRenderer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nBuild
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontAtlas_nBuild
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getTexDataAsAlpha8
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_getTexDataAsAlpha8
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexDataAsRGBA32
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nGetTexDataAsRGBA32
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nIsBuilt
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontAtlas_nIsBuilt
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetTexID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetTexID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesDefault
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesDefault
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesGreek
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesGreek
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesKorean
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesKorean
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesJapanese
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesJapanese
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesChineseFull
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesChineseFull
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesChineseSimplifiedCommon
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesChineseSimplifiedCommon
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesCyrillic
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesCyrillic
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesThai
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesThai
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesVietnamese
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesVietnamese
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddCustomRectRegular
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nAddCustomRectRegular
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddCustomRectFontGlyph
 * Signature: (JSIIF)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nAddCustomRectFontGlyph__JSIIF
  (JNIEnv *, jobject, jlong, jshort, jint, jint, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddCustomRectFontGlyph
 * Signature: (JSIIFFF)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nAddCustomRectFontGlyph__JSIIFFF
  (JNIEnv *, jobject, jlong, jshort, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nGetFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexMinWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nGetTexMinWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetTexMinWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetTexMinWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexMinHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nGetTexMinHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetTexMinHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetTexMinHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexMaxWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nGetTexMaxWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetTexMaxWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetTexMaxWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexMaxHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nGetTexMaxHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetTexMaxHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetTexMaxHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexGlyphPadding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nGetTexGlyphPadding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetTexGlyphPadding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetTexGlyphPadding
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontAtlas_nGetLocked
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nSetLocked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nSetLocked
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
