/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFontConfig */

#ifndef _Included_imgui_ImFontConfig
#define _Included_imgui_ImFontConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFontConfig
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontConfig_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getFontData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_imgui_ImFontConfig_getFontData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setFontData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setFontData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetFontDataSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_nGetFontDataSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetFontDataSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetFontDataSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetFontDataOwnedByAtlas
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontConfig_nGetFontDataOwnedByAtlas
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetFontDataOwnedByAtlas
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetFontDataOwnedByAtlas
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetFontNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_nGetFontNo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetFontNo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetFontNo
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetSizePixels
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetSizePixels
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetSizePixels
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetSizePixels
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetOversampleH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_nGetOversampleH
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetOversampleH
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetOversampleH
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetOversampleV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_nGetOversampleV
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetOversampleV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetOversampleV
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetPixelSnapH
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontConfig_nGetPixelSnapH
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetPixelSnapH
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetPixelSnapH
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetGlyphExtraAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetGlyphExtraAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphExtraAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphExtraAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetGlyphOffset
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nGetGlyphOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetGlyphOffsetX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetGlyphOffsetX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetGlyphOffsetY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetGlyphOffsetY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphRanges
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphRanges
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphExcludeRanges
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphExcludeRanges
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetGlyphMinAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetGlyphMinAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphMinAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphMinAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetGlyphMaxAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetGlyphMaxAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphMaxAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphMaxAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetMergeMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontConfig_nGetMergeMode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetMergeMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetMergeMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetFontLoaderFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_nGetFontLoaderFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetFontLoaderFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetFontLoaderFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetRasterizerMultiply
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetRasterizerMultiply
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetRasterizerMultiply
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetRasterizerMultiply
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetRasterizerDensity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_nGetRasterizerDensity
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetRasterizerDensity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetRasterizerDensity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetEllipsisChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFontConfig_nGetEllipsisChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetEllipsisChar
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetEllipsisChar
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nGetDstFont
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontConfig_nGetDstFont
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetDstFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetDstFont
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
