/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imnodes_ImNodesIO */

#ifndef _Included_imgui_extension_imnodes_ImNodesIO
#define _Included_imgui_extension_imnodes_ImNodesIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imnodes_ImNodesIO
 * Method:    nGetAltMouseButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodesIO_nGetAltMouseButton
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesIO
 * Method:    nSetAltMouseButton
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesIO_nSetAltMouseButton
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodesIO
 * Method:    nGetAutoPanningSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesIO_nGetAutoPanningSpeed
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesIO
 * Method:    nSetAutoPanningSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesIO_nSetAutoPanningSpeed
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
