/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotSpec */

#ifndef _Included_imgui_extension_implot_ImPlotSpec
#define _Included_imgui_extension_implot_ImPlotSpec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotSpec_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nFreeArrays
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nFreeArrays
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetLineColor
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetLineColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetLineColorX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetLineColorX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetLineColorY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetLineColorY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetLineColorZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetLineColorZ
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetLineColorW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetLineColorW
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetLineColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetLineColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetLineWeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetLineWeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetLineWeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetLineWeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFillColor
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFillColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFillColorX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFillColorX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFillColorY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFillColorY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFillColorZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFillColorZ
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFillColorW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFillColorW
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetFillColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetFillColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFillAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFillAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetFillAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetFillAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarker
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarker
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarker
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarker
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarkerSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarkerSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerLineColor
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerLineColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerLineColorX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerLineColorX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerLineColorY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerLineColorY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerLineColorZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerLineColorZ
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerLineColorW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerLineColorW
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarkerLineColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarkerLineColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerFillColor
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerFillColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerFillColorX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerFillColorX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerFillColorY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerFillColorY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerFillColorZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerFillColorZ
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetMarkerFillColorW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetMarkerFillColorW
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarkerFillColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarkerFillColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetOffset
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetOffset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetStride
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetStride
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetStride
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetStride
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nGetFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotSpec_nGetFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetLineColors
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetLineColors
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetFillColors
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetFillColors
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarkerSizes
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarkerSizes
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarkerLineColors
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarkerLineColors
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlotSpec
 * Method:    nSetMarkerFillColors
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotSpec_nSetMarkerFillColors
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
