/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiPlatformMonitor */

#ifndef _Included_imgui_ImGuiPlatformMonitor
#define _Included_imgui_ImGuiPlatformMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetMainPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nGetMainPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetMainPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetMainPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetMainPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetMainPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nSetMainPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nSetMainPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetMainSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nGetMainSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetMainSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetMainSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetMainSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetMainSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nSetMainSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nSetMainSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetWorkPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nGetWorkPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetWorkPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetWorkPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetWorkPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetWorkPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nSetWorkPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nSetWorkPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetWorkSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nGetWorkSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetWorkSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetWorkSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetWorkSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetWorkSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nSetWorkSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nSetWorkSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nGetDpiScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_nGetDpiScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    nSetDpiScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_nSetDpiScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    setPlatformHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_setPlatformHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getPlatformHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiPlatformMonitor_getPlatformHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
