/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imguizmo_ImGuizmo */

#ifndef _Included_imgui_extension_imguizmo_ImGuizmo
#define _Included_imgui_extension_imguizmo_ImGuizmo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetDrawList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetDrawList__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetDrawList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetDrawList__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nBeginFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nBeginFrame
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetImGuiContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetImGuiContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nIsOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nIsOver__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nIsUsing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nIsUsing
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nDecomposeMatrixToComponents
 * Signature: ([F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nDecomposeMatrixToComponents
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nRecomposeMatrixFromComponents
 * Signature: ([F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nRecomposeMatrixFromComponents
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetRect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetOrthographic
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetOrthographic
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nDrawCubes
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nDrawCubes___3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nDrawCubes
 * Signature: ([F[F[FI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nDrawCubes___3F_3F_3FI
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nDrawGrid
 * Signature: ([F[F[FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nDrawGrid
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloat);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nManipulate
 * Signature: ([F[FII[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nManipulate___3F_3FII_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nManipulate
 * Signature: ([F[FII[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nManipulate___3F_3FII_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nManipulate
 * Signature: ([F[FII[F[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nManipulate___3F_3FII_3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nManipulate
 * Signature: ([F[FII[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nManipulate___3F_3FII_3F_3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nManipulate
 * Signature: ([F[FII[F[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nManipulate___3F_3FII_3F_3F_3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nViewManipulate
 * Signature: ([FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nViewManipulate
  (JNIEnv *, jclass, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetID
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nIsOver
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nIsOver__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nSetGizmoSizeClipSpace
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nSetGizmoSizeClipSpace
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_imguizmo_ImGuizmo
 * Method:    nAllowAxisFlip
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguizmo_ImGuizmo_nAllowAxisFlip
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
