/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiPlatformIO */

#ifndef _Included_imgui_ImGuiPlatformIO
#define _Included_imgui_ImGuiPlatformIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    nInit
 * Signature: (Limgui/ImGuiViewport;Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_nInit
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformCreateWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformCreateWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformDestroyWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformDestroyWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformShowWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformShowWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformSetWindowPos
 * Signature: (Limgui/callback/ImPlatformFuncViewportImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformSetWindowPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformGetWindowPos
 * Signature: (Limgui/callback/ImPlatformFuncViewportSuppImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformGetWindowPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformSetWindowSize
 * Signature: (Limgui/callback/ImPlatformFuncViewportImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformSetWindowSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformGetWindowSize
 * Signature: (Limgui/callback/ImPlatformFuncViewportSuppImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformGetWindowSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformSetWindowFocus
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformSetWindowFocus
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformGetWindowFocus
 * Signature: (Limgui/callback/ImPlatformFuncViewportSuppBoolean;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformGetWindowFocus
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformGetWindowMinimized
 * Signature: (Limgui/callback/ImPlatformFuncViewportSuppBoolean;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformGetWindowMinimized
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformSetWindowTitle
 * Signature: (Limgui/callback/ImPlatformFuncViewportString;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformSetWindowTitle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformSetWindowAlpha
 * Signature: (Limgui/callback/ImPlatformFuncViewportFloat;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformSetWindowAlpha
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformUpdateWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformUpdateWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformRenderWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformRenderWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformSwapBuffers
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformSwapBuffers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformGetWindowDpiScale
 * Signature: (Limgui/callback/ImPlatformFuncViewportSuppFloat;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformGetWindowDpiScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setPlatformOnChangedViewport
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setPlatformOnChangedViewport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setRendererCreateWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setRendererCreateWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setRendererDestroyWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setRendererDestroyWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setRendererSetWindowPos
 * Signature: (Limgui/callback/ImPlatformFuncViewportImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setRendererSetWindowPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setRendererRenderWindow
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setRendererRenderWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    setRendererSwapBuffers
 * Signature: (Limgui/callback/ImPlatformFuncViewport;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_setRendererSwapBuffers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    resizeMonitors
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_resizeMonitors
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    getMonitorsSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiPlatformIO_getMonitorsSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    pushMonitors
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformIO_pushMonitors
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    nGetMonitors
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiPlatformIO_nGetMonitors
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    getViewportsSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiPlatformIO_getViewportsSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformIO
 * Method:    nGetViewports
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiPlatformIO_nGetViewports
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
