/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiListClipper */

#ifndef _Included_imgui_ImGuiListClipper
#define _Included_imgui_ImGuiListClipper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiListClipper_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nGetCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiListClipper_nGetCtx
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nSetCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nSetCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nGetDisplayStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiListClipper_nGetDisplayStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nSetDisplayStart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nSetDisplayStart
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nGetDisplayEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiListClipper_nGetDisplayEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nSetDisplayEnd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nSetDisplayEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nGetItemsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiListClipper_nGetItemsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nGetItemsHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiListClipper_nGetItemsHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nGetStartPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiListClipper_nGetStartPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nBegin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nBegin__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nBegin
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nBegin__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nStep
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiListClipper_nStep
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nIncludeItemByIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nIncludeItemByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nIncludeItemsByIndex
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nIncludeItemsByIndex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiListClipper
 * Method:    nForEach
 * Signature: (IILimgui/callback/ImListClipperCallback;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_nForEach
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
