/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_texteditor_TextEditor */

#ifndef _Included_imgui_extension_texteditor_TextEditor
#define _Included_imgui_extension_texteditor_TextEditor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditor_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetTabSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetTabSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetLanguage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetLanguage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetTabSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_nGetTabSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetInsertSpacesOnTabs
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetInsertSpacesOnTabs
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsInsertSpacesOnTabs
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsInsertSpacesOnTabs
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetLineSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetLineSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLineSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLineSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetReadOnlyEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetReadOnlyEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsReadOnlyEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsReadOnlyEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetAutoIndentEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetAutoIndentEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsAutoIndentEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsAutoIndentEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowWhitespacesEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowWhitespacesEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowWhitespacesEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowWhitespacesEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowSpacesEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowSpacesEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowSpacesEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowSpacesEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowTabsEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowTabsEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowTabsEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowTabsEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowLineNumbersEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowLineNumbersEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowLineNumbersEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowLineNumbersEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowScrollbarMiniMapEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowScrollbarMiniMapEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowScrollbarMiniMapEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowScrollbarMiniMapEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowPanScrollIndicatorEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowPanScrollIndicatorEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowPanScrollIndicatorEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowPanScrollIndicatorEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetShowMatchingBrackets
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetShowMatchingBrackets
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsShowingMatchingBrackets
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsShowingMatchingBrackets
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetCompletePairedGlyphs
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetCompletePairedGlyphs
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsCompletingPairedGlyphs
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsCompletingPairedGlyphs
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetOverwriteEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetOverwriteEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsOverwriteEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsOverwriteEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetMiddleMousePanMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetMiddleMousePanMode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetMiddleMouseScrollMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetMiddleMouseScrollMode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsMiddleMousePanMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsMiddleMousePanMode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_nGetText
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetCursorText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_nGetCursorText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLineText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLineText
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetSectionText
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_nGetSectionText
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nReplaceSectionText
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nReplaceSectionText
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIsEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nIsEmpty
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLineCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLineCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nRender
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nRender__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nRender
 * Signature: (Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nRender__Ljava_lang_String_2FF
  (JNIEnv *, jobject, jstring, jfloat, jfloat);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nRender
 * Signature: (Ljava/lang/String;FFZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nRender__Ljava_lang_String_2FFZ
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetFocus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetFocus
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nCut
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCopy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nCopy
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nPaste
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nPaste
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nUndo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nUndo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nRedo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nRedo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCanUndo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nCanUndo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCanRedo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nCanRedo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetUndoIndex
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditor_nGetUndoIndex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetCursor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetCursor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectAll
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectLine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectLine
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectLines
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectLines
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectRegion
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectRegion
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectToBrackets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectToBrackets__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectToBrackets
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectToBrackets__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGrowSelectionsToCurlyBrackets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nGrowSelectionsToCurlyBrackets
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nShrinkSelectionsToCurlyBrackets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nShrinkSelectionsToCurlyBrackets
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nAddNextOccurrence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nAddNextOccurrence
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectAllOccurrences
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectAllOccurrences
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nAnyCursorHasSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nAnyCursorHasSelection
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nAllCursorsHaveSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nAllCursorsHaveSelection
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCurrentCursorHasSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nCurrentCursorHasSelection
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nClearCursors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nClearCursors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetNumberOfCursors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditor_nGetNumberOfCursors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetMainCursorPosition
 * Signature: (Limgui/extension/texteditor/TextEditorCursorPosition;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nGetMainCursorPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetCurrentCursorPosition
 * Signature: (Limgui/extension/texteditor/TextEditorCursorPosition;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nGetCurrentCursorPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetCursorPosition
 * Signature: (Limgui/extension/texteditor/TextEditorCursorPosition;J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nGetCursorPosition
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetCursorSelection
 * Signature: (Limgui/extension/texteditor/TextEditorCursorSelection;J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nGetCursorSelection
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetMainCursorSelection
 * Signature: (Limgui/extension/texteditor/TextEditorCursorSelection;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nGetMainCursorSelection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetWordAtScreenPos
 * Signature: (FF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_nGetWordAtScreenPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nScrollToLine
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nScrollToLine
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetFirstVisibleLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_nGetFirstVisibleLine
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLastVisibleLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLastVisibleLine
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetFirstVisibleColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_nGetFirstVisibleColumn
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLastVisibleColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLastVisibleColumn
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLineHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLineHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetGlyphWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_texteditor_TextEditor_nGetGlyphWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectFirstOccurrenceOf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectFirstOccurrenceOf__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectFirstOccurrenceOf
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectFirstOccurrenceOf__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectFirstOccurrenceOf
 * Signature: (Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectFirstOccurrenceOf__Ljava_lang_String_2ZZ
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectNextOccurrenceOf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectNextOccurrenceOf__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectNextOccurrenceOf
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectNextOccurrenceOf__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectNextOccurrenceOf
 * Signature: (Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectNextOccurrenceOf__Ljava_lang_String_2ZZ
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectAllOccurrencesOf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectAllOccurrencesOf__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectAllOccurrencesOf
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectAllOccurrencesOf__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectAllOccurrencesOf
 * Signature: (Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectAllOccurrencesOf__Ljava_lang_String_2ZZ
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nReplaceTextInCurrentCursor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nReplaceTextInCurrentCursor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nReplaceTextInAllCursors
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nReplaceTextInAllCursors
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nOpenFindReplaceWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nOpenFindReplaceWindow
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCloseFindReplaceWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nCloseFindReplaceWindow
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetFindButtonLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetFindButtonLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetFindAllButtonLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetFindAllButtonLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetReplaceButtonLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetReplaceButtonLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetReplaceAllButtonLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetReplaceAllButtonLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nHasFindString
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nHasFindString
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nFindNext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nFindNext
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nFindAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nFindAll
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nAddMarker
 * Signature: (IIILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nAddMarker
  (JNIEnv *, jobject, jint, jint, jint, jstring, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nClearMarkers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nClearMarkers
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nHasMarkers
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nHasMarkers
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nIndentLines
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nIndentLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nDeindentLines
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nDeindentLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nMoveUpLines
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nMoveUpLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nMoveDownLines
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nMoveDownLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nToggleComments
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nToggleComments
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectionToLowerCase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectionToLowerCase
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSelectionToUpperCase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSelectionToUpperCase
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nStripTrailingWhitespaces
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nStripTrailingWhitespaces
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nTabsToSpaces
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nTabsToSpaces
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSpacesToTabs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSpacesToTabs
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getPalette
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetPalette
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetPalette
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getDefaultPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getDefaultPalette
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetDefaultPalette
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetDefaultPalette
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getDarkPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getDarkPalette
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getLightPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getLightPalette
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getPaletteColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_getPaletteColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setPaletteColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setPaletteColor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLanguage
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLanguage
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nHasLanguage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_nHasLanguage
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetLanguageName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_nGetLanguageName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetImGuiContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetImGuiContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetUserData
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetUserData
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nGetUserData
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditor_nGetUserData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
