/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiInputTextCallbackData */

#ifndef _Included_imgui_ImGuiInputTextCallbackData
#define _Included_imgui_ImGuiInputTextCallbackData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetCtx
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetCtx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetEventFlag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetEventFlag
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetEventChar
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetEventChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetEventChar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetEventChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetEventKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetEventKey
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetBuf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetBuf
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetBuf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetBuf
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetBufTextLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetBufTextLen
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetBufTextLen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetBufTextLen
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetBufDirty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetBufDirty
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetBufDirty
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetBufDirty
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetCursorPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetCursorPos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetCursorPos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetCursorPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetSelectionStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetSelectionStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetSelectionStart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetSelectionStart
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nGetSelectionEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_nGetSelectionEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSetSelectionEnd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSetSelectionEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nDeleteChars
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nDeleteChars
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nInsertChars
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nInsertChars
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nSelectAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nSelectAll
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nClearSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_nClearSelection
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    nHasSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiInputTextCallbackData_nHasSelection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
