/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_lwjgl3_glfw_ImGuiImplGlfwNative */

#ifndef _Included_imgui_lwjgl3_glfw_ImGuiImplGlfwNative
#define _Included_imgui_lwjgl3_glfw_ImGuiImplGlfwNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_lwjgl3_glfw_ImGuiImplGlfwNative
 * Method:    win32hideFromTaskBar
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_lwjgl3_glfw_ImGuiImplGlfwNative_win32hideFromTaskBar
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
