/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_internal_ImGuiWindow */

#ifndef _Included_imgui_internal_ImGuiWindow
#define _Included_imgui_internal_ImGuiWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_internal_ImGuiWindow
 * Method:    nGetScrollbarX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiWindow_nGetScrollbarX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiWindow
 * Method:    nGetScrollbarY
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiWindow_nGetScrollbarY
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
