/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiTextFilter */

#ifndef _Included_imgui_ImGuiTextFilter
#define _Included_imgui_ImGuiTextFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiTextFilter_nCreate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_nDraw__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nDraw
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_nDraw__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nDraw
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_nDraw__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nDraw
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_nDraw__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nPassFilter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_nPassFilter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nBuild
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_nBuild
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_nClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nIsActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_nIsActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    getInputBuffer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiTextFilter_getInputBuffer
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    setInputBuffer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_setInputBuffer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nGetCountGrep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiTextFilter_nGetCountGrep
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nSetCountGrep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_nSetCountGrep
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
