/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiStyle */

#ifndef _Included_imgui_ImGuiStyle
#define _Included_imgui_ImGuiStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiStyle
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiStyle_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisabledAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetDisabledAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetDisabledAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetDisabledAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFontScaleMain
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetFontScaleMain
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetFontScaleMain
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetFontScaleMain
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFontScaleDpi
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetFontScaleDpi
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetFontScaleDpi
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetFontScaleDpi
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetWindowPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetWindowPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetWindowPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetWindowRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetWindowRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetWindowBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetWindowBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowMinSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetWindowMinSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowMinSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowMinSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowMinSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowMinSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetWindowMinSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetWindowMinSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowTitleAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetWindowTitleAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowTitleAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowTitleAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowTitleAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetWindowTitleAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetWindowTitleAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetWindowTitleAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetWindowMenuButtonPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_nGetWindowMenuButtonPosition
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetWindowMenuButtonPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetWindowMenuButtonPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetChildRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetChildRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetChildRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetChildRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetChildBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetChildBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetChildBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetChildBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetPopupRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetPopupRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetPopupRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetPopupRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetPopupBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetPopupBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetPopupBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetPopupBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFramePadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetFramePadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFramePaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetFramePaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFramePaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetFramePaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetFramePadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetFramePadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFrameRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetFrameRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetFrameRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetFrameRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetFrameBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetFrameBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetFrameBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetFrameBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetItemSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetItemSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetItemSpacingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetItemSpacingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetItemSpacingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetItemSpacingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetItemSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetItemSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetItemInnerSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetItemInnerSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetItemInnerSpacingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetItemInnerSpacingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetItemInnerSpacingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetItemInnerSpacingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetItemInnerSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetItemInnerSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetCellPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetCellPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetCellPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetCellPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetCellPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetCellPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetCellPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetCellPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTouchExtraPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetTouchExtraPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTouchExtraPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTouchExtraPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTouchExtraPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTouchExtraPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTouchExtraPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTouchExtraPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetIndentSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetIndentSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetIndentSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetIndentSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetColumnsMinSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetColumnsMinSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetColumnsMinSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetColumnsMinSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetScrollbarSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetScrollbarSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetScrollbarSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetScrollbarSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetScrollbarRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetScrollbarRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetScrollbarRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetScrollbarRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetGrabMinSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetGrabMinSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetGrabMinSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetGrabMinSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetGrabRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetGrabRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetGrabRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetGrabRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetLogSliderDeadzone
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetLogSliderDeadzone
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetLogSliderDeadzone
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetLogSliderDeadzone
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTabRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTabRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTabRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTabRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTabBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTabBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTabBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTabBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTabCloseButtonMinWidthSelected
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTabCloseButtonMinWidthSelected
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTabCloseButtonMinWidthSelected
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTabCloseButtonMinWidthSelected
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTabCloseButtonMinWidthUnselected
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTabCloseButtonMinWidthUnselected
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTabCloseButtonMinWidthUnselected
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTabCloseButtonMinWidthUnselected
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetColorButtonPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_nGetColorButtonPosition
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetColorButtonPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetColorButtonPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetButtonTextAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetButtonTextAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetButtonTextAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetButtonTextAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetButtonTextAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetButtonTextAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetButtonTextAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetButtonTextAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSelectableTextAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetSelectableTextAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSelectableTextAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSelectableTextAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSelectableTextAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSelectableTextAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetSelectableTextAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetSelectableTextAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetImageRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetImageRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetImageRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetImageRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetImageBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetImageBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetImageBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetImageBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTreeLinesFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_nGetTreeLinesFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTreeLinesFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTreeLinesFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTreeLinesSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTreeLinesSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTreeLinesSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTreeLinesSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetTreeLinesRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetTreeLinesRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetTreeLinesRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetTreeLinesRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetColorMarkerSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetColorMarkerSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetColorMarkerSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetColorMarkerSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSeparatorSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetSeparatorSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetSeparatorSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetSeparatorTextBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetSeparatorTextBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetSeparatorTextAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetSeparatorTextAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetSeparatorTextPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetSeparatorTextPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetSeparatorTextPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetSeparatorTextPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisplayWindowPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetDisplayWindowPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisplayWindowPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetDisplayWindowPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisplayWindowPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetDisplayWindowPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetDisplayWindowPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetDisplayWindowPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisplaySafeAreaPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nGetDisplaySafeAreaPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisplaySafeAreaPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetDisplaySafeAreaPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDisplaySafeAreaPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetDisplaySafeAreaPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetDisplaySafeAreaPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetDisplaySafeAreaPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetDockingSeparatorSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetDockingSeparatorSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetDockingSeparatorSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetDockingSeparatorSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetMouseCursorScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetMouseCursorScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetMouseCursorScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetMouseCursorScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetAntiAliasedLines
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStyle_nGetAntiAliasedLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetAntiAliasedLines
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetAntiAliasedLines
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetAntiAliasedLinesUseTex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStyle_nGetAntiAliasedLinesUseTex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetAntiAliasedLinesUseTex
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetAntiAliasedLinesUseTex
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetAntiAliasedFill
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStyle_nGetAntiAliasedFill
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetAntiAliasedFill
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetAntiAliasedFill
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetCurveTessellationTol
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetCurveTessellationTol
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetCurveTessellationTol
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetCurveTessellationTol
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetCircleTessellationMaxError
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetCircleTessellationMaxError
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetCircleTessellationMaxError
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetCircleTessellationMaxError
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetColors
 * Signature: ()[Limgui/ImVec4;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_ImGuiStyle_nGetColors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetColors
 * Signature: ([Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetColors
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getColor
 * Signature: (ILimgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getColor
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColor__IFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColor
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColor__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColor__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetHoverStationaryDelay
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetHoverStationaryDelay
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetHoverStationaryDelay
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetHoverStationaryDelay
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetHoverDelayShort
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetHoverDelayShort
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetHoverDelayShort
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetHoverDelayShort
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetHoverDelayNormal
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_nGetHoverDelayNormal
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetHoverDelayNormal
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetHoverDelayNormal
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetHoverFlagsForTooltipMouse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_nGetHoverFlagsForTooltipMouse
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetHoverFlagsForTooltipMouse
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetHoverFlagsForTooltipMouse
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nGetHoverFlagsForTooltipNav
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_nGetHoverFlagsForTooltipNav
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nSetHoverFlagsForTooltipNav
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nSetHoverFlagsForTooltipNav
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    nScaleAllSizes
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_nScaleAllSizes
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
