/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiViewport */

#ifndef _Included_imgui_ImGuiViewport
#define _Included_imgui_ImGuiViewport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiViewport_nGetID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetID
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiViewport_nGetFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nGetPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nGetSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nGetWorkPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetWorkPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetWorkPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetWorkPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetWorkPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nGetWorkSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetWorkSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetWorkSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetWorkSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetWorkSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetDpiScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetDpiScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetDpiScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetDpiScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetParentViewportId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiViewport_nGetParentViewportId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetParentViewportId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetParentViewportId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetDrawData
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiViewport_nGetDrawData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetDrawData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetDrawData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setRendererUserData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setRendererUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getRendererUserData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_imgui_ImGuiViewport_getRendererUserData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformUserData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformUserData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_imgui_ImGuiViewport_getPlatformUserData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiViewport_getPlatformHandle
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformHandleRaw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformHandleRaw
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformHandleRaw
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiViewport_getPlatformHandleRaw
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPlatformWindowCreated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_nGetPlatformWindowCreated
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetPlatformWindowCreated
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetPlatformWindowCreated
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPlatformRequestMove
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_nGetPlatformRequestMove
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetPlatformRequestMove
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetPlatformRequestMove
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPlatformRequestResize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_nGetPlatformRequestResize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetPlatformRequestResize
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetPlatformRequestResize
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetPlatformRequestClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_nGetPlatformRequestClose
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nSetPlatformRequestClose
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nSetPlatformRequestClose
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetCenter
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nGetCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetCenterX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetCenterX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetCenterY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetCenterY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkCenter
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_nGetWorkCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkCenterX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetWorkCenterX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetWorkCenterY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_nGetWorkCenterY
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
