/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_memedit_MemoryEditor */

#ifndef _Included_imgui_extension_memedit_MemoryEditor
#define _Included_imgui_extension_memedit_MemoryEditor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_memedit_MemoryEditor_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOpen
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOpen
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOpen
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetReadOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetReadOnly
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetReadOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetReadOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetCols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetCols
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetCols
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetCols
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptShowOptions
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptShowOptions
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptShowOptions
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptShowOptions
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptShowDataPreview
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptShowDataPreview
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptShowDataPreview
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptShowDataPreview
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptShowHexII
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptShowHexII
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptShowHexII
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptShowHexII
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptShowAscii
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptShowAscii
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptShowAscii
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptShowAscii
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptGreyOutZeroes
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptGreyOutZeroes
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptGreyOutZeroes
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptGreyOutZeroes
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptUpperCaseHex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptUpperCaseHex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptUpperCaseHex
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptUpperCaseHex
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptMidColsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptMidColsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptMidColsCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptMidColsCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptAddrDigitsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptAddrDigitsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptAddrDigitsCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptAddrDigitsCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetOptFooterExtraHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetOptFooterExtraHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetOptFooterExtraHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetOptFooterExtraHeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGetHighlightColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_memedit_MemoryEditor_nGetHighlightColor
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nSetHighlightColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nSetHighlightColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nGotoAddrAndHighlight
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nGotoAddrAndHighlight
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nCalcSizes
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nCalcSizes
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawWindow
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawWindow__Ljava_lang_String_2JJ
  (JNIEnv *, jobject, jstring, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawWindow
 * Signature: (Ljava/lang/String;JJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawWindow__Ljava_lang_String_2JJJ
  (JNIEnv *, jobject, jstring, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawContents
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawContents__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawContents
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawContents__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawOptionsLine
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawOptionsLine
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawPreviewLine
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawPreviewLine
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
