/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_internal_ImGui */

#ifndef _Included_imgui_internal_ImGui
#define _Included_imgui_internal_ImGui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_internal_ImGui
 * Method:    nInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nInit
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetCurrentWindowRead
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nGetCurrentWindowRead
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetCurrentWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nGetCurrentWindow
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFindWindowByID
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nFindWindowByID
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFindWindowByName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nFindWindowByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nUpdateWindowParentAndRootLinks
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nUpdateWindowParentAndRootLinks
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcWindowNextAutoFitSize
 * Signature: (Limgui/ImVec2;J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nCalcWindowNextAutoFitSize
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcWindowNextAutoFitSizeX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nCalcWindowNextAutoFitSizeX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcWindowNextAutoFitSizeY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nCalcWindowNextAutoFitSizeY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsWindowChildOf
 * Signature: (JJZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsWindowChildOf
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsWindowWithinBeginStackOf
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsWindowWithinBeginStackOf
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsWindowAbove
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsWindowAbove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsWindowNavFocusable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsWindowNavFocusable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowPos
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowPos__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowPos
 * Signature: (JFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowPos__JFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowSize
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowSize__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowSize
 * Signature: (JFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowSize__JFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowCollapsed
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowCollapsed__JZ
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowCollapsed
 * Signature: (JZI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowCollapsed__JZI
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetWindowHitTestHole
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetWindowHitTestHole
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nWindowRectAbsToRel
 * Signature: (Limgui/internal/ImRect;JFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nWindowRectAbsToRel
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nWindowRectRelToAbs
 * Signature: (Limgui/internal/ImRect;JFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nWindowRectRelToAbs
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFocusWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nFocusWindow__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFocusWindow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nFocusWindow__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFocusTopMostWindowUnderOne
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nFocusTopMostWindowUnderOne
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nBringWindowToFocusFront
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nBringWindowToFocusFront
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nBringWindowToDisplayFront
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nBringWindowToDisplayFront
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nBringWindowToDisplayBack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nBringWindowToDisplayBack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nBringWindowToDisplayBehind
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nBringWindowToDisplayBehind
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFindWindowDisplayIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nFindWindowDisplayIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nFindBottomMostVisibleWindowWithinBeginStack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nFindBottomMostVisibleWindowWithinBeginStack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetCurrentFont
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetCurrentFont
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetDefaultFont
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nGetDefaultFont
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetForegroundDrawList
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nGetForegroundDrawList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nInitialize
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nShutdown
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nUpdateInputEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nUpdateInputEvents
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nUpdateHoveredWindowAndCaptureFlags
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nUpdateHoveredWindowAndCaptureFlags
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nStartMouseMovingWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nStartMouseMovingWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nStartMouseMovingWindowOrNode
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nStartMouseMovingWindowOrNode
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nUpdateMouseMovingWindowNewFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nUpdateMouseMovingWindowNewFrame
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nUpdateMouseMovingWindowEndFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nUpdateMouseMovingWindowEndFrame
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetViewportPlatformMonitor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nGetViewportPlatformMonitor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetNextWindowScroll
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetNextWindowScroll
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetScrollX
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetScrollX
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetScrollY
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetScrollY
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetScrollFromPosX
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetScrollFromPosX
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetScrollFromPosY
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetScrollFromPosY
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToItem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollToItem__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToItem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollToItem__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollToRect__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRect
 * Signature: (JFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollToRect__JFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRectEx
 * Signature: (Limgui/ImVec2;JFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollToRectEx__Limgui_ImVec2_2JFFFF
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRectExX
 * Signature: (JFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nScrollToRectExX__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRectExY
 * Signature: (JFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nScrollToRectExY__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRectEx
 * Signature: (Limgui/ImVec2;JFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollToRectEx__Limgui_ImVec2_2JFFFFI
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRectExX
 * Signature: (JFFFFI)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nScrollToRectExX__JFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollToRectExY
 * Signature: (JFFFFI)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nScrollToRectExY__JFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetItemStatusFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetItemStatusFlags
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetItemFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetItemFlags
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetActiveID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetActiveID
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetFocusID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetFocusID
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetActiveID
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetActiveID
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetFocusID
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetFocusID
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nClearActiveID
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nClearActiveID
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetHoveredID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetHoveredID
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetHoveredID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetHoveredID
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nKeepAliveID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nKeepAliveID
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nMarkItemEdited
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nMarkItemEdited
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nPushOverrideID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nPushOverrideID
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetIDWithSeed
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetIDWithSeed
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nItemSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nItemSize__FF
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nItemSize
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nItemSize__FFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nItemSize
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nItemSize__FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nItemSize
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nItemSize__FFFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nItemHoverable
 * Signature: (FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nItemHoverable
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsWindowContentHoverable
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsWindowContentHoverable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsClippedEx
 * Signature: (FFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsClippedEx
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSetLastItemData
 * Signature: (IIIFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSetLastItemData
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcItemSize
 * Signature: (Limgui/ImVec2;FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nCalcItemSize
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcItemSizeX
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nCalcItemSizeX
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcItemSizeY
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nCalcItemSizeY
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCalcWrapWidthForPos
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nCalcWrapWidthForPos
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nPushMultiItemsWidths
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nPushMultiItemsWidths
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nIsItemToggledSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nIsItemToggledSelection
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nPushItemFlag
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nPushItemFlag
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nPopItemFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nPopItemFlag
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderDockWindow
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderDockWindow
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderGetNode
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nDockBuilderGetNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderGetCentralNode
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nDockBuilderGetCentralNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderAddNode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderAddNode__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderAddNode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderAddNode__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderAddNode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderAddNode__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderRemoveNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderRemoveNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderRemoveNodeDockedWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderRemoveNodeDockedWindows__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderRemoveNodeDockedWindows
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderRemoveNodeDockedWindows__IZ
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderRemoveNodeChildNodes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderRemoveNodeChildNodes
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSetNodePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderSetNodePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSetNodeSize
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderSetNodeSize
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSplitNode
 * Signature: (IIF[I[I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderSplitNode
  (JNIEnv *, jclass, jint, jint, jfloat, jintArray, jintArray);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderCopyWindowSettings
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderCopyWindowSettings
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderFinish
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nDockBuilderFinish
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableOpenContextMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTableOpenContextMenu__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableOpenContextMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTableOpenContextMenu__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableSetColumnWidth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTableSetColumnWidth
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableSetColumnSortDirection
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTableSetColumnSortDirection
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableGetHoveredColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nTableGetHoveredColumn
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableGetHoveredRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nTableGetHoveredRow
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTableGetHeaderRowHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_nTableGetHeaderRowHeight
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTablePushBackgroundChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTablePushBackgroundChannel
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTablePopBackgroundChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTablePopBackgroundChannel
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTextEx
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTextEx__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTextEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTextEx__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nTextEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nTextEx__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nButtonEx
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nButtonEx__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nButtonEx
 * Signature: (Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nButtonEx__Ljava_lang_String_2FF
  (JNIEnv *, jclass, jstring, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nButtonEx
 * Signature: (Ljava/lang/String;FFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nButtonEx__Ljava_lang_String_2FFI
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nButtonEx
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nButtonEx__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nArrowButtonEx
 * Signature: (Ljava/lang/String;IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nArrowButtonEx__Ljava_lang_String_2IFF
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nArrowButtonEx
 * Signature: (Ljava/lang/String;IFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nArrowButtonEx__Ljava_lang_String_2IFFI
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nImageButtonEx
 * Signature: (IJFFFFFFFFFFFFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nImageButtonEx
  (JNIEnv *, jclass, jint, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSeparatorEx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSeparatorEx__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSeparatorEx
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSeparatorEx__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSeparatorTextEx
 * Signature: (ILjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nSeparatorTextEx
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCloseButton
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nCloseButton
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nCollapseButton
 * Signature: (IFFJ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nCollapseButton
  (JNIEnv *, jclass, jint, jfloat, jfloat, jlong);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nScrollbar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nScrollbar
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetWindowScrollbarRect
 * Signature: (Limgui/internal/ImRect;JI)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nGetWindowScrollbarRect
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetWindowScrollbarID
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetWindowScrollbarID
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetWindowResizeCornerID
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetWindowResizeCornerID
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetWindowResizeBorderID
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nGetWindowResizeBorderID
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nButtonBehavior
 * Signature: (FFFFI[Z[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nButtonBehavior__FFFFI_3Z_3Z
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jbooleanArray, jbooleanArray);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nButtonBehavior
 * Signature: (FFFFI[Z[ZI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nButtonBehavior__FFFFI_3Z_3ZI
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jbooleanArray, jbooleanArray, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSplitterBehavior
 * Signature: (FFFFII[F[FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nSplitterBehavior__FFFFII_3F_3FFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint, jfloatArray, jfloatArray, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSplitterBehavior
 * Signature: (FFFFII[F[FFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nSplitterBehavior__FFFFII_3F_3FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSplitterBehavior
 * Signature: (FFFFII[F[FFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nSplitterBehavior__FFFFII_3F_3FFFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSplitterBehavior
 * Signature: (FFFFII[F[FFFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nSplitterBehavior__FFFFII_3F_3FFFFFI
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nShadeVertsTransformPos
 * Signature: (JIIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nShadeVertsTransformPos
  (JNIEnv *, jclass, jlong, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
