/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiKeyData */

#ifndef _Included_imgui_ImGuiKeyData
#define _Included_imgui_ImGuiKeyData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiKeyData_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nGetDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiKeyData_nGetDown
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nSetDown
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiKeyData_nSetDown
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nGetDownDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiKeyData_nGetDownDuration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nSetDownDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiKeyData_nSetDownDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nGetDownDurationPrev
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiKeyData_nGetDownDurationPrev
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nSetDownDurationPrev
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiKeyData_nSetDownDurationPrev
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nGetAnalogValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiKeyData_nGetAnalogValue
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiKeyData
 * Method:    nSetAnalogValue
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiKeyData_nSetAnalogValue
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
