/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imnodes_ImNodesStyle */

#ifndef _Included_imgui_extension_imnodes_ImNodesStyle
#define _Included_imgui_extension_imnodes_ImNodesStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetGridSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetGridSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetGridSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetGridSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetNodeCornerRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetNodeCornerRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetNodeCornerRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetNodeCornerRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetNodePadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetNodePadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetNodePaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetNodePaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetNodePaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetNodePaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetNodePadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetNodePadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetNodeBorderThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetNodeBorderThickness
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetNodeBorderThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetNodeBorderThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetLinkThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetLinkThickness
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetLinkThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetLinkThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetLinkLineSegmentsPerLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetLinkLineSegmentsPerLength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetLinkLineSegmentsPerLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetLinkLineSegmentsPerLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetLinkHoverDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetLinkHoverDistance
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetLinkHoverDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetLinkHoverDistance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetPinCircleRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetPinCircleRadius
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetPinCircleRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetPinCircleRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetPinQuadSideLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetPinQuadSideLength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetPinQuadSideLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetPinQuadSideLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetPinTriangleSideLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetPinTriangleSideLength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetPinTriangleSideLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetPinTriangleSideLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetPinLineThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetPinLineThickness
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetPinLineThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetPinLineThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetPinHoverRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetPinHoverRadius
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetPinHoverRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetPinHoverRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetPinOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetPinOffset
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetPinOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetPinOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetMiniMapPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetMiniMapPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetMiniMapPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetMiniMapPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetMiniMapPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetMiniMapPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetMiniMapPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetMiniMapPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetMiniMapOffset
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetMiniMapOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetMiniMapOffsetX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetMiniMapOffsetX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetMiniMapOffsetY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetMiniMapOffsetY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetMiniMapOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetMiniMapOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetColors
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetColors__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nGetColors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nGetColors__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetColors
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetColors___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    nSetColors
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_nSetColors__II
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
