/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_internal_ImGuiDockNode */

#ifndef _Included_imgui_internal_ImGuiDockNode
#define _Included_imgui_internal_ImGuiDockNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetID
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSharedFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetSharedFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetSharedFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetSharedFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLocalFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLocalFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLocalFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLocalFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLocalFlagsInWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLocalFlagsInWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLocalFlagsInWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLocalFlagsInWindows
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetMergedFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetMergedFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetParentNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetParentNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetParentNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetParentNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetChildNodeFirst
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetChildNodeFirst
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetChildNodeFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetChildNodeFirst
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetChildNodeSecond
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetChildNodeSecond
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetChildNodeSecond
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetChildNodeSecond
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nGetPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_nGetPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_nGetPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nGetSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_nGetSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_nGetSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSizeRef
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nGetSizeRef
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSizeRefX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_nGetSizeRefX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSizeRefY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_nGetSizeRefY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetSizeRef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetSizeRef
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSplitAxis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetSplitAxis
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWindowClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetWindowClass
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLastBgColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLastBgColor
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLastBgColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLastBgColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetHostWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetHostWindow
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetHostWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetHostWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetVisibleWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetVisibleWindow
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetVisibleWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetVisibleWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetCentralNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetCentralNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetCentralNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetCentralNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetOnlyNodeWithWindows
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetOnlyNodeWithWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetOnlyNodeWithWindows
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetOnlyNodeWithWindows
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLastFrameAlive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLastFrameAlive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLastFrameAlive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLastFrameAlive
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLastFrameActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLastFrameActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLastFrameActive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLastFrameActive
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLastFrameFocused
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLastFrameFocused
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLastFrameFocused
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLastFrameFocused
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetLastFocusedNodeId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetLastFocusedNodeId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetLastFocusedNodeId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetLastFocusedNodeId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetSelectedTabId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetSelectedTabId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetSelectedTabId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetSelectedTabId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWantCloseTabId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetWantCloseTabId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWantCloseTabId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWantCloseTabId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetAuthorityForPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetAuthorityForPos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetAuthorityForPos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetAuthorityForPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetAuthorityForSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetAuthorityForSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetAuthorityForSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetAuthorityForSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetAuthorityForViewport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_nGetAuthorityForViewport
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetAuthorityForViewport
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetAuthorityForViewport
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetIsVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetIsVisible
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetIsVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetIsVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetIsFocused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetIsFocused
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetIsFocused
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetIsFocused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetHasCloseButton
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetHasCloseButton
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetHasCloseButton
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetHasCloseButton
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetHasWindowMenuButton
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetHasWindowMenuButton
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetHasWindowMenuButton
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetHasWindowMenuButton
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetHasCentralNodeChild
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetHasCentralNodeChild
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetHasCentralNodeChild
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetHasCentralNodeChild
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWantCloseAll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetWantCloseAll
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWantCloseAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWantCloseAll
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWantLockSizeOnce
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetWantLockSizeOnce
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWantLockSizeOnce
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWantLockSizeOnce
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWantMouseMove
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetWantMouseMove
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWantMouseMove
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWantMouseMove
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWantHiddenTabBarUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetWantHiddenTabBarUpdate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWantHiddenTabBarUpdate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWantHiddenTabBarUpdate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWantHiddenTabBarToggle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nGetWantHiddenTabBarToggle
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWantHiddenTabBarToggle
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWantHiddenTabBarToggle
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsRootNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsRootNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsDockSpace
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsDockSpace
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsFloatingNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsFloatingNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsCentralNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsCentralNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsHiddenTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsHiddenTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsNoTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsNoTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsSplitNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsSplitNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsLeafNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsLeafNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nIsEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_nIsEmpty
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nRect
 * Signature: (Limgui/internal/ImRect;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nUpdateMergedFlags
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nUpdateMergedFlags
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
