/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFontGlyph */

#ifndef _Included_imgui_ImFontGlyph
#define _Included_imgui_ImFontGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFontGlyph
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontGlyph_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetColored
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontGlyph_nGetColored
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetColored
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetColored
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetVisible
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontGlyph_nGetVisible
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetVisible
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetVisible
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetCodepoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontGlyph_nGetCodepoint
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetCodepoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetCodepoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetX0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetX0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetX0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetX0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetY0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetY0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetY0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetY0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetX1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetX1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetX1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetX1
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetY1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetY1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetY1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetY1
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetU0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetU0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetU0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetU0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetV0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetV0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetV0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetV0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetU1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetU1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetU1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetU1
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nGetV1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_nGetV1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    nSetV1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_nSetV1
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
