/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_binding_ImGuiStructDestroyable */

#ifndef _Included_imgui_binding_ImGuiStructDestroyable
#define _Included_imgui_binding_ImGuiStructDestroyable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_binding_ImGuiStructDestroyable
 * Method:    nDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_binding_ImGuiStructDestroyable_nDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
