/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiTableColumnSortSpecs */

#ifndef _Included_imgui_ImGuiTableColumnSortSpecs
#define _Included_imgui_ImGuiTableColumnSortSpecs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiTableColumnSortSpecs
 * Method:    nGetColumnUserID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiTableColumnSortSpecs_nGetColumnUserID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTableColumnSortSpecs
 * Method:    nGetColumnIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiTableColumnSortSpecs_nGetColumnIndex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTableColumnSortSpecs
 * Method:    nGetSortOrder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiTableColumnSortSpecs_nGetSortOrder
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTableColumnSortSpecs
 * Method:    nGetSortDirection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiTableColumnSortSpecs_nGetSortDirection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
