/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImDrawData */

#ifndef _Included_imgui_ImDrawData
#define _Included_imgui_ImDrawData
#ifdef __cplusplus
extern "C" {
#endif
#undef imgui_ImDrawData_RESIZE_FACTOR
#define imgui_ImDrawData_RESIZE_FACTOR 5000L
/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferElemCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferElemCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferClipRect
 * Signature: (Limgui/ImVec4;II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferClipRect
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferTextureId
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferTextureId
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferVtxOffset
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferVtxOffset
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferIdxOffset
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferIdxOffset
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListIdxBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListIdxBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetCmdListIdxBufferData
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetCmdListIdxBufferData
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListVtxBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListVtxBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetCmdListVtxBufferData
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetCmdListVtxBufferData
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    sizeOfImDrawVert
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_sizeOfImDrawVert
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImDrawData
 * Method:    sizeOfImDrawIdx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_sizeOfImDrawIdx
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImDrawData_nGetValid
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetCmdListsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_nGetCmdListsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetTotalIdxCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_nGetTotalIdxCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetTotalVtxCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_nGetTotalVtxCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetDisplayPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetDisplayPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetDisplayPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_nGetDisplayPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetDisplayPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_nGetDisplayPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetDisplaySize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetDisplaySize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetDisplaySizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_nGetDisplaySizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetDisplaySizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_nGetDisplaySizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetFramebufferScale
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetFramebufferScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetFramebufferScaleX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_nGetFramebufferScaleX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetFramebufferScaleY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_nGetFramebufferScaleY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetOwnerViewport
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImDrawData_nGetOwnerViewport
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nAddDrawList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nAddDrawList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImDrawData
 * Method:    nDeIndexAllBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nDeIndexAllBuffers
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nScaleClipRects
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nScaleClipRects
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
