/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_memedit_MemoryEditorSizes */

#ifndef _Included_imgui_extension_memedit_MemoryEditorSizes
#define _Included_imgui_extension_memedit_MemoryEditorSizes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetAddrDigitsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetAddrDigitsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetAddrDigitsCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetAddrDigitsCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetLineHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetLineHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetLineHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetLineHeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetGlyphWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetGlyphWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetGlyphWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetGlyphWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetHexCellWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetHexCellWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetHexCellWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetHexCellWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetSpacingBetweenMidCols
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetSpacingBetweenMidCols
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetSpacingBetweenMidCols
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetSpacingBetweenMidCols
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetOffsetHexMinX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetOffsetHexMinX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetOffsetHexMinX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetOffsetHexMinX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetOffsetHexMaxX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetOffsetHexMaxX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetOffsetHexMaxX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetOffsetHexMaxX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetOffsetAsciiMinX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetOffsetAsciiMinX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetOffsetAsciiMinX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetOffsetAsciiMinX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetOffsetAsciiMaxX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetOffsetAsciiMaxX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetOffsetAsciiMaxX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetOffsetAsciiMaxX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nGetWindowWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nGetWindowWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nSetWindowWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nSetWindowWidth
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
