/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imguiknobs_ImGuiKnobs */

#ifndef _Included_imgui_extension_imguiknobs_ImGuiKnobs
#define _Included_imgui_extension_imguiknobs_ImGuiKnobs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFF
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFF
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2I
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;IF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2IF
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint, jfloat);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;IFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2IFI
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint, jfloat, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;IFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2IFII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFLjava/lang/String;IFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFLjava_lang_String_2IFII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jstring, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFIFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFIFII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFIFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFIFII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFFII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFI
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;FII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2FII
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2III
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3FFFFLjava_lang_String_2II
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[III)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3III
  (JNIEnv *, jclass, jstring, jintArray, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIF
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2I
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;IF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2IF
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint, jfloat);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;IFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2IFI
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint, jfloat, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;IFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2IFII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIILjava/lang/String;IFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIILjava_lang_String_2IFII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jstring, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIIFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIIFII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFIFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFIFII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFFII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFI
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;FII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2FII
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2III
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob__Ljava_lang_String_2_3IIIFLjava_lang_String_2II
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
