/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditor */

#ifndef _Included_imgui_extension_nodeditor_NodeEditor
#define _Included_imgui_extension_nodeditor_NodeEditor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSetCurrentEditor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSetCurrentEditor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetCurrentEditor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetCurrentEditor
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nCreateEditor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nCreateEditor__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nCreateEditor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nCreateEditor__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nDestroyEditor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nDestroyEditor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetStyle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetStyleColorName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetStyleColorName
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPushStyleColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPushStyleColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPopStyleColor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPopStyleColor__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPopStyleColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPopStyleColor__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPushStyleVar
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPushStyleVar__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPushStyleVar
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPushStyleVar__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPushStyleVar
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPushStyleVar__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPopStyleVar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPopStyleVar__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPopStyleVar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPopStyleVar__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBegin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBegin__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBegin
 * Signature: (Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBegin__Ljava_lang_String_2FF
  (JNIEnv *, jclass, jstring, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEnd
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginPin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginPin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPinRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPinRect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPinPivotRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPinPivotRect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPinPivotSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPinPivotSize
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPinPivotScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPinPivotScale
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPinPivotAlignment
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPinPivotAlignment
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEndPin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEndPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGroup
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGroup
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEndNode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEndNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginGroupHint
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginGroupHint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetGroupMin
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetGroupMin
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetGroupMinX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetGroupMinX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetGroupMinY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetGroupMinY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetGroupMax
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetGroupMax
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetGroupMaxX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetGroupMaxX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetGroupMaxY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetGroupMaxY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHintForegroundDrawList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHintForegroundDrawList
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHintBackgroundDrawList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHintBackgroundDrawList
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEndGroupHint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEndGroupHint
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeBackgroundDrawList
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeBackgroundDrawList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nLink
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nLink__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nLink
 * Signature: (JJJFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nLink__JJJFFFF
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nLink
 * Signature: (JJJFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nLink__JJJFFFFF
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nLink
 * Signature: (JJJF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nLink__JJJF
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nFlow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nFlow__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nFlow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nFlow__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginCreate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginCreate__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginCreate
 * Signature: (FFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginCreate__FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginCreate
 * Signature: (FFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginCreate__FFFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginCreate
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginCreate__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewLink
 * Signature: ([J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewLink___3J_3J
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewLink
 * Signature: ([J[JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewLink___3J_3JFFFF
  (JNIEnv *, jclass, jlongArray, jlongArray, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewLink
 * Signature: ([J[JFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewLink___3J_3JFFFFF
  (JNIEnv *, jclass, jlongArray, jlongArray, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewNode
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewNode___3J
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewNode
 * Signature: ([JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewNode___3JFFFF
  (JNIEnv *, jclass, jlongArray, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewNode
 * Signature: ([JFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewNode___3JFFFFF
  (JNIEnv *, jclass, jlongArray, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptNewItem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptNewItem__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptNewItem
 * Signature: (FFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptNewItem__FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptNewItem
 * Signature: (FFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptNewItem__FFFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nRejectNewItem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nRejectNewItem__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nRejectNewItem
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nRejectNewItem__FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nRejectNewItem
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nRejectNewItem__FFFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEndCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEndCreate
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginDelete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginDelete
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryDeletedLink
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryDeletedLink___3J
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryDeletedLink
 * Signature: ([J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryDeletedLink___3J_3J
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryDeletedLink
 * Signature: ([J[J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryDeletedLink___3J_3J_3J
  (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryDeletedNode
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryDeletedNode
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptDeletedItem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptDeletedItem__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptDeletedItem
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptDeletedItem__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nRejectDeletedItem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nRejectDeletedItem
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEndDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEndDelete
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSetNodePosition
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSetNodePosition
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSetGroupSize
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSetGroupSize
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodePosition
 * Signature: (Limgui/ImVec2;J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodePosition
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodePositionX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodePositionX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodePositionY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodePositionY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeSize
 * Signature: (Limgui/ImVec2;J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeSize
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeSizeX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeSizeX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeSizeY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeSizeY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nCenterNodeOnScreen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nCenterNodeOnScreen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSetNodeZPosition
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSetNodeZPosition
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeZPosition
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeZPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nRestoreNodeState
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nRestoreNodeState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSuspend
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSuspend
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nResume
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nIsSuspended
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nIsSuspended
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nIsActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nIsActive
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nHasSelectionChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nHasSelectionChanged
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetSelectedObjectCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetSelectedObjectCount
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetSelectedNodes
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetSelectedNodes
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetSelectedLinks
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetSelectedLinks
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nIsNodeSelected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nIsNodeSelected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nIsLinkSelected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nIsLinkSelected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nClearSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nClearSelection
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSelectNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSelectNode__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSelectNode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSelectNode__JZ
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSelectLink
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSelectLink__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSelectLink
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSelectLink__JZ
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nDeselectNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nDeselectNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nDeselectLink
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nDeselectLink
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nDeleteNode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nDeleteNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nDeleteLink
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nDeleteLink
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nHasAnyLinksNode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nHasAnyLinksNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nHasAnyLinksPin
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nHasAnyLinksPin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBreakLinksNode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBreakLinksNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBreakLinksPin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBreakLinksPin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nNavigateToContent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nNavigateToContent__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nNavigateToContent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nNavigateToContent__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nNavigateToSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nNavigateToSelection__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nNavigateToSelection
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nNavigateToSelection__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nNavigateToSelection
 * Signature: (ZF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nNavigateToSelection__ZF
  (JNIEnv *, jclass, jboolean, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nNavigateToSelection
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nNavigateToSelection__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowNodeContextMenu
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowNodeContextMenu
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowPinContextMenu
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowPinContextMenu
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowLinkContextMenu
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowLinkContextMenu
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodeWithContextMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodeWithContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getPinWithContextMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getPinWithContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getLinkWithContextMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getLinkWithContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowBackgroundContextMenu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowBackgroundContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEnableShortcuts
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEnableShortcuts
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAreShortcutsEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAreShortcutsEnabled
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nBeginShortcut
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nBeginShortcut
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptCut
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptCut
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptCopy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptCopy
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptPaste
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptPaste
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptDuplicate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptDuplicate
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nAcceptCreateNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nAcceptCreateNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetActionContextSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetActionContextSize
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetActionContextNodes
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetActionContextNodes
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetActionContextLinks
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetActionContextLinks
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nEndShortcut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nEndShortcut
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetCurrentZoom
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetCurrentZoom
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHoveredNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHoveredNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHoveredPin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHoveredPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHoveredLink
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHoveredLink
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetDoubleClickedNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetDoubleClickedNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetDoubleClickedPin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetDoubleClickedPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetDoubleClickedLink
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetDoubleClickedLink
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nIsBackgroundClicked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nIsBackgroundClicked
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nIsBackgroundDoubleClicked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nIsBackgroundDoubleClicked
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetLinkPins
 * Signature: (J[J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetLinkPins
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nPinHadAnyLinks
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nPinHadAnyLinks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetScreenSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetScreenSize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetScreenSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetScreenSizeX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetScreenSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetScreenSizeY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nScreenToCanvas
 * Signature: (Limgui/ImVec2;FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nScreenToCanvas
  (JNIEnv *, jclass, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nScreenToCanvasX
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nScreenToCanvasX
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nScreenToCanvasY
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nScreenToCanvasY
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nCanvasToScreen
 * Signature: (Limgui/ImVec2;FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nCanvasToScreen
  (JNIEnv *, jclass, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nCanvasToScreenX
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nCanvasToScreenX
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nCanvasToScreenY
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_nCanvasToScreenY
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeCount
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetOrderedNodeIds
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetOrderedNodeIds
  (JNIEnv *, jclass, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
