/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imnodes_ImNodes */

#ifndef _Included_imgui_extension_imnodes_ImNodes
#define _Included_imgui_extension_imnodes_ImNodes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSetImGuiContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSetImGuiContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nCreateContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodes_nCreateContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nDestroyContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nDestroyContext__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nDestroyContext__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodes_nGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSetCurrentContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSetCurrentContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextCreate
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextGetPanning
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextGetPanning
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextGetPanningX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextGetPanningX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextGetPanningY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextGetPanningY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextResetPanning
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextResetPanning
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextMoveToNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextMoveToNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetIO
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodes_nGetIO
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetStyle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodes_nGetStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nStyleColorsDark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nStyleColorsDark__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nStyleColorsDark
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nStyleColorsDark__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nStyleColorsClassic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nStyleColorsClassic__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nStyleColorsClassic
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nStyleColorsClassic__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nStyleColorsLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nStyleColorsLight__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nStyleColorsLight
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nStyleColorsLight__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginNodeEditor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginNodeEditor
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEndNodeEditor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEndNodeEditor
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nMiniMap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nMiniMap__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nMiniMap
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nMiniMap__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nMiniMap
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nMiniMap__FI
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPushColorStyle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPushColorStyle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPopColorStyle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPopColorStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPushStyleVar
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPushStyleVar__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPushStyleVar
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPushStyleVar__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPopStyleVar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPopStyleVar
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEndNode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEndNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeDimensions
 * Signature: (Limgui/ImVec2;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeDimensions
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeDimensionsX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeDimensionsX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeDimensionsY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeDimensionsY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginNodeTitleBar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginNodeTitleBar
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEndNodeTitleBar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEndNodeTitleBar
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginInputAttribute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginInputAttribute__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginInputAttribute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginInputAttribute__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEndInputAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEndInputAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginOutputAttribute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginOutputAttribute__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginOutputAttribute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginOutputAttribute__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEndOutputAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEndOutputAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nBeginStaticAttribute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nBeginStaticAttribute
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEndStaticAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEndStaticAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPushAttributeFlag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPushAttributeFlag
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nPopAttributeFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nPopAttributeFlag
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLink
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLink
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSetNodeDraggable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSetNodeDraggable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSetNodeScreenSpacePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSetNodeScreenSpacePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSetNodeEditorSpacePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSetNodeEditorSpacePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSetNodeGridSpacePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSetNodeGridSpacePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeScreenSpacePos
 * Signature: (Limgui/ImVec2;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeScreenSpacePos
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeScreenSpacePosX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeScreenSpacePosX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeScreenSpacePosY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeScreenSpacePosY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeEditorSpacePos
 * Signature: (Limgui/ImVec2;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeEditorSpacePos
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeEditorSpacePosX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeEditorSpacePosX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeEditorSpacePosY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeEditorSpacePosY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeGridSpacePos
 * Signature: (Limgui/ImVec2;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeGridSpacePos
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeGridSpacePosX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeGridSpacePosX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetNodeGridSpacePosY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_nGetNodeGridSpacePosY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSnapNodeToGrid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSnapNodeToGrid
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsEditorHovered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsEditorHovered
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsNodeHovered
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsNodeHovered
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkHovered
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkHovered
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsPinHovered
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsPinHovered
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getHoveredNode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getHoveredNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getHoveredLink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getHoveredLink
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getHoveredPin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getHoveredPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nNumSelectedNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_nNumSelectedNodes
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nNumSelectedLinks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_nNumSelectedLinks
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetSelectedNodes
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nGetSelectedNodes
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetSelectedLinks
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nGetSelectedLinks
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nClearNodeSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nClearNodeSelection__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nClearLinkSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nClearLinkSelection__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSelectNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSelectNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nClearNodeSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nClearNodeSelection__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsNodeSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsNodeSelected
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSelectLink
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSelectLink
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nClearLinkSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nClearLinkSelection__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkSelected
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsAttributeActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsAttributeActive
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsAnyAttributeActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsAnyAttributeActive__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsAnyAttributeActive
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsAnyAttributeActive___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getActiveAttribute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getActiveAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkStarted
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkStarted
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDropped
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDropped__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDropped
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDropped___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDropped
 * Signature: ([IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDropped___3IZ
  (JNIEnv *, jclass, jintArray, jboolean);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDropped
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDropped__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkCreated
 * Signature: ([I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkCreated___3I_3I
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkCreated
 * Signature: ([I[I[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkCreated___3I_3I_3Z
  (JNIEnv *, jclass, jintArray, jintArray, jbooleanArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkCreated
 * Signature: ([I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkCreated___3I_3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkCreated
 * Signature: ([I[I[I[I[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkCreated___3I_3I_3I_3I_3Z
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jbooleanArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDestroyed
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDestroyed
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSaveCurrentEditorStateToIniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imnodes_ImNodes_nSaveCurrentEditorStateToIniString
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSaveEditorStateToIniString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imnodes_ImNodes_nSaveEditorStateToIniString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLoadCurrentEditorStateFromIniString
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLoadCurrentEditorStateFromIniString
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLoadEditorStateFromIniString
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLoadEditorStateFromIniString
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSaveCurrentEditorStateToIniFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSaveCurrentEditorStateToIniFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSaveEditorStateToIniFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSaveEditorStateToIniFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLoadCurrentEditorStateFromIniFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLoadCurrentEditorStateFromIniFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLoadEditorStateFromIniFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLoadEditorStateFromIniFile
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
