/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiTableSortSpecs */

#ifndef _Included_imgui_ImGuiTableSortSpecs
#define _Included_imgui_ImGuiTableSortSpecs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiTableSortSpecs
 * Method:    nGetSpecs
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_imgui_ImGuiTableSortSpecs_nGetSpecs
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTableSortSpecs
 * Method:    nGetSpecsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiTableSortSpecs_nGetSpecsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTableSortSpecs
 * Method:    nGetSpecsDirty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTableSortSpecs_nGetSpecsDirty
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTableSortSpecs
 * Method:    nSetSpecsDirty
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTableSortSpecs_nSetSpecsDirty
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
