/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiWindowClass */

#ifndef _Included_imgui_ImGuiWindowClass
#define _Included_imgui_ImGuiWindowClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiWindowClass_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetClassId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetClassId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetClassId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetClassId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetParentViewportId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetParentViewportId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetParentViewportId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetParentViewportId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetFocusRouteParentWindowId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetFocusRouteParentWindowId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetFocusRouteParentWindowId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetFocusRouteParentWindowId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetViewportFlagsOverrideSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetViewportFlagsOverrideSet
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetViewportFlagsOverrideSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetViewportFlagsOverrideSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetViewportFlagsOverrideClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetViewportFlagsOverrideClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetViewportFlagsOverrideClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetViewportFlagsOverrideClear
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetTabItemFlagsOverrideSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetTabItemFlagsOverrideSet
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetTabItemFlagsOverrideSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetTabItemFlagsOverrideSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetDockNodeFlagsOverrideSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_nGetDockNodeFlagsOverrideSet
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetDockNodeFlagsOverrideSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetDockNodeFlagsOverrideSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetDockingAlwaysTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiWindowClass_nGetDockingAlwaysTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetDockingAlwaysTabBar
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetDockingAlwaysTabBar
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nGetDockingAllowUnclassed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiWindowClass_nGetDockingAllowUnclassed
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nSetDockingAllowUnclassed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_nSetDockingAllowUnclassed
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
