/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditorStyle */

#ifndef _Included_imgui_extension_nodeditor_NodeEditorStyle
#define _Included_imgui_extension_nodeditor_NodeEditorStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodePadding
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodePadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodePaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodePaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodePaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodePaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodePaddingZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodePaddingZ
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodePaddingW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodePaddingW
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetNodePadding
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetNodePadding
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodeRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodeRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetNodeRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetNodeRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetNodeBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetNodeBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetNodeBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetNodeBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetHoveredNodeBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetHoveredNodeBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetHoveredNodeBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetHoveredNodeBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetHoverNodeBorderOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetHoverNodeBorderOffset
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetHoverNodeBorderOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetHoverNodeBorderOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetSelectedNodeBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetSelectedNodeBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetSelectedNodeBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetSelectedNodeBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetSelectedNodeBorderOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetSelectedNodeBorderOffset
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetSelectedNodeBorderOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetSelectedNodeBorderOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPinRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPinRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPinRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPinRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPinBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPinBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPinBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPinBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetLinkStrength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetLinkStrength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetLinkStrength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetLinkStrength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetSourceDirection
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetSourceDirection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetSourceDirectionX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetSourceDirectionX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetSourceDirectionY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetSourceDirectionY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetSourceDirection
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetSourceDirection
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetTargetDirection
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetTargetDirection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetTargetDirectionX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetTargetDirectionX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetTargetDirectionY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetTargetDirectionY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetTargetDirection
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetTargetDirection
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetScrollDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetScrollDuration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetScrollDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetScrollDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetFlowMarkerDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetFlowMarkerDistance
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetFlowMarkerDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetFlowMarkerDistance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetFlowSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetFlowSpeed
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetFlowSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetFlowSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetFlowDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetFlowDuration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetFlowDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetFlowDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotAlignment
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotAlignment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotAlignmentX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotAlignmentX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotAlignmentY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotAlignmentY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPivotAlignment
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPivotAlignment
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPivotSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPivotSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotScale
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotScaleX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotScaleX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPivotScaleY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPivotScaleY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPivotScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPivotScale
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPinCorners
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPinCorners
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPinCorners
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPinCorners
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPinRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPinRadius
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPinRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPinRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPinArrowSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPinArrowSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPinArrowSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPinArrowSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetPinArrowWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetPinArrowWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetPinArrowWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetPinArrowWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetGroupRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetGroupRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetGroupRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetGroupRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetGroupBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetGroupBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetGroupBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetGroupBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetHighlightConnectedLinks
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetHighlightConnectedLinks
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetHighlightConnectedLinks
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetHighlightConnectedLinks
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetSnapLinkToPinDir
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetSnapLinkToPinDir
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetSnapLinkToPinDir
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetSnapLinkToPinDir
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nGetColors
 * Signature: ()[Limgui/ImVec4;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nGetColors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    nSetColors
 * Signature: ([Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_nSetColors
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
