/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotStyle */

#ifndef _Included_imgui_extension_implot_ImPlotStyle
#define _Included_imgui_extension_implot_ImPlotStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotStyle_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickLen
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickLen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickLenX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickLenX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickLenY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickLenY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMajorTickLen
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMajorTickLen
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickLen
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickLen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickLenX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickLenX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickLenY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickLenY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorTickLen
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorTickLen
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMajorTickSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMajorTickSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorTickSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorTickSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorGridSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorGridSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorGridSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorGridSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorGridSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorGridSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMajorGridSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMajorGridSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorGridSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorGridSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorGridSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorGridSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorGridSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorGridSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorGridSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorGridSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLabelPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLabelPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLabelPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLabelPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLabelPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLabelPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLabelPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLabelPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLegendPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLegendPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendInnerPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendInnerPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendInnerPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendInnerPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendInnerPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendInnerPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLegendInnerPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLegendInnerPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendSpacingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendSpacingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendSpacingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendSpacingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLegendSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLegendSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMousePosPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMousePosPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMousePosPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMousePosPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMousePosPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMousePosPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMousePosPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMousePosPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetAnnotationPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetAnnotationPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetAnnotationPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetAnnotationPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetAnnotationPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetAnnotationPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetAnnotationPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetAnnotationPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetFitPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetFitPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetFitPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetFitPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetFitPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetFitPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetFitPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetFitPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotDefaultSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotDefaultSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotDefaultSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotDefaultSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotDefaultSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotDefaultSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotDefaultSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotDefaultSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotMinSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotMinSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotMinSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotMinSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotMinSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotMinSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotMinSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotMinSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetDigitalPadding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetDigitalPadding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetDigitalPadding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetDigitalPadding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetDigitalSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetDigitalSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetDigitalSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetDigitalSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetColors
 * Signature: ()[Limgui/ImVec4;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetColors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetColors
 * Signature: ([Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetColors
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetColormap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetColormap
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetColormap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetColormap
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetUseLocalTime
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetUseLocalTime
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetUseLocalTime
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetUseLocalTime
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetUseISO8601
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetUseISO8601
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetUseISO8601
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetUseISO8601
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetUse24HourClock
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetUse24HourClock
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetUse24HourClock
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetUse24HourClock
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
