/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImDrawList */

#ifndef _Included_imgui_ImDrawList
#define _Included_imgui_ImDrawList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImDrawList
 * Method:    nGetFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawList_nGetFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nSetFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nSetFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetVtxCurrentIdx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawList_nGetVtxCurrentIdx
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPushClipRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPushClipRect__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPushClipRect
 * Signature: (FFFFZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPushClipRect__FFFFZ
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPushClipRectFullScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPushClipRectFullScreen
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPopClipRect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPopClipRect
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPushTextureID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPushTextureID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPopTextureID
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPopTextureID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetClipRectMin
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nGetClipRectMin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetClipRectMinX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_nGetClipRectMinX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetClipRectMinY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_nGetClipRectMinY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetClipRectMax
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nGetClipRectMax
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetClipRectMaxX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_nGetClipRectMaxX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nGetClipRectMaxY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_nGetClipRectMaxY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddLine
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddLine__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddLine
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddLine__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRect
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRect__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRect
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRect__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRect
 * Signature: (FFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRect__FFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRect
 * Signature: (FFFFIFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRect__FFFFIFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRect
 * Signature: (FFFFIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRect__FFFFIIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRect
 * Signature: (FFFFIFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRect__FFFFIFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRectFilled
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRectFilled__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRectFilled
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRectFilled__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRectFilled
 * Signature: (FFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRectFilled__FFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRectFilled
 * Signature: (FFFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRectFilled__FFFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddRectFilledMultiColor
 * Signature: (FFFFIIII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddRectFilledMultiColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddQuad
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddQuad__FFFFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddQuad
 * Signature: (FFFFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddQuad__FFFFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddQuadFilled
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddQuadFilled
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddTriangle
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddTriangle__FFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddTriangle
 * Signature: (FFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddTriangle__FFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddTriangleFilled
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddTriangleFilled
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddCircle
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddCircle__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddCircle
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddCircle__FFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddCircle
 * Signature: (FFFIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddCircle__FFFIIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddCircle
 * Signature: (FFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddCircle__FFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddCircleFilled
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddCircleFilled__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddCircleFilled
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddCircleFilled__FFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddNgon
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddNgon__FFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddNgon
 * Signature: (FFFIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddNgon__FFFIIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddNgonFilled
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddNgonFilled
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipse
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipse__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipse
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipse__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipse
 * Signature: (FFFFIFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipse__FFFFIFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipse
 * Signature: (FFFFIFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipse__FFFFIFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipseFilled
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipseFilled__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipseFilled
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipseFilled__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddEllipseFilled
 * Signature: (FFFFIFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddEllipseFilled__FFFFIFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (FFILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__FFILjava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jint, jstring);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (FFILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__FFILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jint, jstring, jstring);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring, jstring);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2Ljava_lang_String_2F
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring, jstring, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;Ljava/lang/String;FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2Ljava_lang_String_2FFFFF
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2FFFFF
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2FFFF
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JIFFILjava/lang/String;Ljava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JIFFILjava_lang_String_2Ljava_lang_String_2FFFF
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jint, jstring, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddBezierCubic
 * Signature: (FFFFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddBezierCubic__FFFFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddBezierCubic
 * Signature: (FFFFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddBezierCubic__FFFFFFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddBezierQuadratic
 * Signature: (FFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddBezierQuadratic__FFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddBezierQuadratic
 * Signature: (FFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddBezierQuadratic__FFFFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddPolyline
 * Signature: ([Limgui/ImVec2;IIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddPolyline
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddConvexPolyFilled
 * Signature: ([Limgui/ImVec2;II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddConvexPolyFilled
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddConcavePolyFilled
 * Signature: ([Limgui/ImVec2;II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddConcavePolyFilled
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImage
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImage__JFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImage
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImage__JFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImage
 * Signature: (JFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImage__JFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImage
 * Signature: (JFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImage__JFFFFFFFFI
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageQuad
 * Signature: (JFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageQuad__JFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageQuad
 * Signature: (JFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageQuad__JFFFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageQuad
 * Signature: (JFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageQuad__JFFFFFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageQuad
 * Signature: (JFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageQuad__JFFFFFFFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageQuad
 * Signature: (JFFFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageQuad__JFFFFFFFFFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageQuad
 * Signature: (JFFFFFFFFFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageQuad__JFFFFFFFFFFFFFFFFI
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageRounded
 * Signature: (JFFFFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageRounded__JFFFFFFFFIF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddImageRounded
 * Signature: (JFFFFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddImageRounded__JFFFFFFFFIFI
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathLineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathLineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathLineToMergeDuplicate
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathLineToMergeDuplicate
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathFillConvex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathFillConvex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathFillConcave
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathFillConcave
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathStroke
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathStroke__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathStroke
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathStroke__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathStroke
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathStroke__IIF
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathStroke
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathStroke__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathArcTo
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathArcTo__FFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathArcTo
 * Signature: (FFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathArcTo__FFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathArcToFast
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathArcToFast
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathEllipticalArcTo
 * Signature: (FFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathEllipticalArcTo__FFFFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathEllipticalArcTo
 * Signature: (FFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathEllipticalArcTo__FFFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathBezierCubicCurveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathBezierCubicCurveTo__FFFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathBezierCubicCurveTo
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathBezierCubicCurveTo__FFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathBezierQuadraticCurveTo
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathBezierQuadraticCurveTo__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathBezierQuadraticCurveTo
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathBezierQuadraticCurveTo__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathRect__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathRect
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathRect__FFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathRect
 * Signature: (FFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathRect__FFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPathRect
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPathRect__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nChannelsSplit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nChannelsSplit
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nChannelsMerge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nChannelsMerge
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    nChannelsSetCurrent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nChannelsSetCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimReserve
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimReserve
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimUnreserve
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimUnreserve
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimRect
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimRect
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimRectUV
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimRectUV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimQuadUV
 * Signature: (FFFFFFFFFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimQuadUV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimWriteVtx
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimWriteVtx
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimWriteIdx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimWriteIdx
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    nPrimVtx
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nPrimVtx
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
