/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_texteditor_TextEditorLanguage */

#ifndef _Included_imgui_extension_texteditor_TextEditorLanguage
#define _Included_imgui_extension_texteditor_TextEditorLanguage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetCaseSensitive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetCaseSensitive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetPreprocess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetPreprocess
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetSingleLineComment
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetSingleLineComment
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetSingleLineCommentAlt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetSingleLineCommentAlt
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetCommentStart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetCommentStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetCommentEnd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetCommentEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetHasSingleQuotedStrings
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetHasSingleQuotedStrings
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetHasDoubleQuotedStrings
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetHasDoubleQuotedStrings
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetOtherStringStart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetOtherStringStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetOtherStringEnd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetOtherStringEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetOtherStringAltStart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetOtherStringAltStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetOtherStringAltEnd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetOtherStringAltEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGetStringEscape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGetStringEscape
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nC
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nCpp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nCpp
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nCs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nCs
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nAngelScript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nAngelScript
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nLua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nLua
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nPython
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nPython
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nGlsl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nGlsl
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nHlsl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nHlsl
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nJson
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nJson
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nMarkdown
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nMarkdown
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguage
 * Method:    nSql
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguage_nSql
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
