/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditorConfig */

#ifndef _Included_imgui_extension_nodeditor_NodeEditorConfig
#define _Included_imgui_extension_nodeditor_NodeEditorConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetSettingsFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetSettingsFile
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetSettingsFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetSettingsFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetCanvasSizeMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetCanvasSizeMode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetCanvasSizeMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetCanvasSizeMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetDragButtonIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetDragButtonIndex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetDragButtonIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetDragButtonIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetSelectButtonIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetSelectButtonIndex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetSelectButtonIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetSelectButtonIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetNavigateButtonIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetNavigateButtonIndex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetNavigateButtonIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetNavigateButtonIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetContextMenuButtonIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetContextMenuButtonIndex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetContextMenuButtonIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetContextMenuButtonIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetEnableSmoothZoom
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetEnableSmoothZoom
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetEnableSmoothZoom
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetEnableSmoothZoom
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nGetSmoothZoomPower
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nGetSmoothZoomPower
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nSetSmoothZoomPower
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nSetSmoothZoomPower
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
