/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiStorage */

#ifndef _Included_imgui_ImGuiStorage
#define _Included_imgui_ImGuiStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiStorage
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiStorage_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_nClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nGetInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStorage_nGetInt__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nGetInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStorage_nGetInt__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nSetInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_nSetInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nGetBool
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStorage_nGetBool__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nGetBool
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStorage_nGetBool__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nSetBool
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_nSetBool
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nGetFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStorage_nGetFloat__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nGetFloat
 * Signature: (IF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStorage_nGetFloat__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nSetFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_nSetFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nBuildSortByKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_nBuildSortByKey
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    nSetAllInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_nSetAllInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
