/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotInputMap */

#ifndef _Included_imgui_extension_implot_ImPlotInputMap
#define _Included_imgui_extension_implot_ImPlotInputMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotInputMap_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetPan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetPan
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetPan
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetPan
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetPanMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetPanMod
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetPanMod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetPanMod
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetFit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetFit
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetFit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetFit
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetSelect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetSelect
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetSelect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetSelect
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetSelectCancel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetSelectCancel
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetSelectCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetSelectCancel
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetSelectMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetSelectMod
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetSelectMod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetSelectMod
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetSelectHorzMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetSelectHorzMod
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetSelectHorzMod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetSelectHorzMod
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetSelectVertMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetSelectVertMod
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetSelectVertMod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetSelectVertMod
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetMenu
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetMenu
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetMenu
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetOverrideMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetOverrideMod
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetOverrideMod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetOverrideMod
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetZoomMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetZoomMod
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetZoomMod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetZoomMod
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nGetZoomRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotInputMap_nGetZoomRate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotInputMap
 * Method:    nSetZoomRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotInputMap_nSetZoomRate
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
