/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiOnceUponAFrame */

#ifndef _Included_imgui_ImGuiOnceUponAFrame
#define _Included_imgui_ImGuiOnceUponAFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiOnceUponAFrame
 * Method:    get
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiOnceUponAFrame_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
