/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFont */

#ifndef _Included_imgui_ImFont
#define _Included_imgui_ImFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFont
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFont_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nGetLegacySize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_nGetLegacySize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetLegacySize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nSetLegacySize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetEllipsisChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFont_nGetEllipsisChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetEllipsisChar
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nSetEllipsisChar
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImFont
 * Method:    nGetFallbackChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFont_nGetFallbackChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetFallbackChar
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nSetFallbackChar
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImFont
 * Method:    nGetScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_nGetScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nSetScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nIsLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFont_nIsLoaded
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nGetDebugName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImFont_nGetDebugName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeA
 * Signature: (Limgui/ImVec2;FFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nCalcTextSizeA__Limgui_ImVec2_2FFFLjava_lang_String_2
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAX
 * Signature: (FFFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_nCalcTextSizeAX__FFFLjava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAY
 * Signature: (FFFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_nCalcTextSizeAY__FFFLjava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeA
 * Signature: (Limgui/ImVec2;FFFLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nCalcTextSizeA__Limgui_ImVec2_2FFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAX
 * Signature: (FFFLjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_nCalcTextSizeAX__FFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAY
 * Signature: (FFFLjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_nCalcTextSizeAY__FFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcWordWrapPositionA
 * Signature: (FLjava/lang/String;Ljava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImFont_nCalcWordWrapPositionA
  (JNIEnv *, jobject, jfloat, jstring, jstring, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderChar
 * Signature: (JFFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderChar
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2F
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;FI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2FI
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jfloat, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
