name: Build imgui Android AArch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y ant openjdk-17-jdk

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Export compiler path
        run: |
          echo "/opt/hostedtoolcache/ndk/r27c/x64/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Patch build xml compiler
        working-directory: imgui-binding/build/jni
        run: |
          sed -i 's#<property name="cCompiler".*#<property name="cCompiler" value="aarch64-linux-android21-clang"/>#' build-linux64.xml

          sed -i 's#<property name="cppCompiler".*#<property name="cppCompiler" value="aarch64-linux-android21-clang++"/>#' build-linux64.xml

          sed -i 's#<property name="compilerPrefix".*#<property name="compilerPrefix" value=""/>#' build-linux64.xml

      - name: Build
        working-directory: imgui-binding/build/jni
        run: ant clean all

      - name: Check output
        working-directory: imgui-binding/build/libsNative/linux64
        run: |
          file libimgui-java64.so
          readelf -d libimgui-java64.so | grep NEEDED || true
          nm -D libimgui-java64.so | grep Java_imgui_moulberry90_ | head || true

      - uses: actions/upload-artifact@v4
        with:
          name: libimgui-java64-android-aarch64
          path: imgui-binding/build/libsNative/linux64/libimgui-java64.so
