name: Build imgui Android AArch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug tree
        run: |
          echo "PWD:"
          pwd
          echo
          echo "ROOT:"
          ls -la
          echo
          echo "DIRECTORIES:"
          find . -maxdepth 5 -type d | sort

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y ant openjdk-17-jdk

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Locate jni dir
        run: |
          find . -type f -name build-linux64.xml

      - name: Stop here
        run: exit 1
